openapi: 3.0.1
info:
  title: Memory Interface Plugin
  version: 'v1'
servers:
  - url: http://localhost:5005
paths:
  /{section}.json:
    get:
      operationId: listTables
      tags:
        - Knowledge
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      responses:
        '200':
          description: OK
  /{section}/{subsection}.json:
    get:
      operationId: listRows
      tags:
        - Knowledge
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: subsection
        in: path
        required: true
        schema:
          type: string
          default: ""
      responses:
        '200':
          description: OK
  /{section}/{subsection}/{id}.json:
    get:
      operationId: getRow
      tags:
        - Knowledge
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: subsection
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /messages/add_message.json:
    post:
      operationId: addMessage
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                    description: "Indicates the successful creation of the resource. In this case, 'Message' refers to the newly created resource."
                    example: "Message inserted"
                  redirect:
                    type: string
                    description: "Path to the newly created resource. The UUID is generated during the creation of the resource."
                    example: "/get_message_by_uuid.json?uuid=9a2b9ea8-6198-4695-806a-814099b6cc2d"

  /messages/get_messages.json:
    get:
      operationId: getMessages
      tags:
        - Messages
      summary: Retrieve all messages
      description: This endpoint retrieves all messages. The messages are returned in descending order by their creation time.
      responses:
        '200':
          description: OK
  /messages/get_message_by_uuid.json:
    get:
      operationId: getMessageByUUID
      tags:
        - Messages
      parameters:
      - name: uuid
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
