openapi: 3.0.1
info:
  title: Memory Interface Plugin
  version: 'v1'
servers:
  - url: http://localhost:5005
paths:
  /{section}.json:
    get:
      operationId: listLongTermMemoryTables
      tags:
        - LongTermMemory
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      responses:
        '200':
          description: OK
  /{section}/{subsection}.json:
    get:
      operationId: listLongTermMemoryRows
      tags:
        - LongTermMemory
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: subsection
        in: path
        required: true
        schema:
          type: string
          default: ""
      responses:
        '200':
          description: OK
  /{section}/{subsection}/{id}.json:
    get:
      operationId: getLongTermMemoryRow
      tags:
        - LongTermMemory
      parameters:
      - name: section
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: subsection
        in: path
        required: true
        schema:
          type: string
          default: ""
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /messages/add_memory.json:
    post:
      operationId: addToShortTermMemory
      tags:
        - ShortTermMemory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                    description: "Indicates the successful creation of the resource. In this case, 'Memory' refers to the newly created resource."
                    example: "Memory inserted"
                  redirect:
                    type: string
                    description: "Path to the newly created resource. The UUID is generated during the creation of the resource."
                    example: "/get_memory_by_uuid.json?uuid=9a2b9ea8-6198-4695-806a-814099b6cc2d"
  /messages/get_memories.json:
    get:
      operationId: getShortTermMemoryMemories
      tags:
        - ShortTermMemory
      summary: Retrieve memory previews
      description: Retrieves previews of all memories. Each preview is the first 50 characters of the memory. You can either limit the number of memories returned or retrieve a specific memory by its UUID, but not both at the same time.
      parameters:
        - name: limit
          in: query
          description: Limit the number of memories returned. This parameter cannot be used with the 'uuid' parameter.
          required: false
          schema:
            type: integer
            default: 10
            nullable: true
        - name: uuid
          in: query
          description: Retrieve a specific memory by its UUID. This parameter cannot be used with the 'limit' parameter.
          required: false
          schema:
            type: string
            default: 1329f4eb-13ab-4c52-b12d-ae1d0d92111e
            nullable: true
      responses:
        '200':
          description: OK
