# docker-compose.yaml
version: '3.9'

services:
  clean-short-term-memory:
    image: python:slim
    container_name: clean-short-term-memory
    working_dir: /app
    volumes:
      - ./../pkg/job-clean-short-term-memory:/app
    environment:
      MEMORY_HOST: 'http://plugin-memory-interface:5005'
      TASK_CREATOR_HOST: 'http://plugin-task-creator:5010'
    ports:
      - "5021:5021"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3
      
  plugin-task-creator:
    image: python:slim
    container_name: plugin-task-creator
    volumes:
      - ./../pkg/plugin-task-creator:/app
    working_dir: /app
    ports:
      - "5010:5010"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://plugin-memory-interface:5005'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  function-ask-with-memory:
    image: python:slim
    container_name: function-ask-with-memory
    volumes:
      - ./../pkg/function-ask-with-memory:/app
    working_dir: /app
    environment:
      RETRIEVAL_API_URL_BASE: 'http://retrieval-app:8080'
      OPENAI_API_KEY: ''
      AI_MODEL: 'gpt-4 or gpt-3.5-turbo'
    ports:
      - "5023:5022"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  function-ask-question:
    image: python:slim
    container_name: function-ask-question
    volumes:
      - ./../pkg/function-ask-question:/app
    working_dir: /app
    environment:
      OPENAI_API_KEY: ''
      AI_MODEL: 'gpt-4 or gpt-3.5-turbo'
    ports:
      - "5022:5022"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

## -- MEMORY SECTION -- ##
  plugin-memory-interface:
    image: python:slim
    container_name: plugin-memory-interface
    volumes:
      - ./../pkg/plugin-memory-interface:/app
    working_dir: /app
    ports:
      - "5005:5005"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://memory:5006'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  memory:
    image: datasetteproject/datasette:0.64.3
    container_name: memory
    volumes:
      - ./../pkg/memory/data:/data
      - ./../pkg/memory:/app
    working_dir: /app
    ports:
      - "5006:5006"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'datasette' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3



networks:
  default:
    name: Yggdrasil