# docker-compose.yaml
version: '3.9'

services:
  function-clean-short-term-memory:
    image: python:slim
    container_name: function-clean-short-term-memory
    volumes:
      - ./../pkg/function-clean-short-term-memory:/app
    working_dir: /app
    ports:
      - "5021:5021"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://plugin-memory-interface:5005'
      TASK_CREATOR_HOST: 'http://plugin-task-creator:5010'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-task-creator:
    image: python:slim
    container_name: plugin-task-creator
    volumes:
      - ./../pkg/plugin-task-creator:/app
    working_dir: /app
    ports:
      - "5010:5010"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://memory:8001'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  memory:
    image: datasetteproject/datasette:0.64.3
    container_name: memory
    volumes:
      - ./../pkg/memory/data:/data
      - ./../pkg/memory:/app
    working_dir: /app
    ports:
      - "5006:8001"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'datasette' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-memory-interface:
    image: python:slim
    container_name: plugin-memory-interface
    volumes:
      - ./../pkg/plugin-memory-interface:/app
    working_dir: /app
    ports:
      - "5005:5005"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://memory:8001'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-send-ntfy:
    image: python:slim
    container_name: plugin-send-ntfy
    working_dir: /app
    volumes:
      - ./../pkg/plugin-send-ntfy:/app
    ports:
      - "5003:5003"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
#    environment:
#      TOPIC: 'string'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3