# docker-compose.yaml
version: '3.9'

name: 'yggdrasil'

services:
## -- MEMORY SECTION -- ##
  plugin-short-term-memory:
    image: python:slim
    container_name: plugin-short-term-memory
    volumes:
      - ./../pkg/plugin-short-term-memory:/app
    working_dir: /app
    ports:
      - "5030:5030"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps curl
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://plugin-memory-interface:5005'
      PORT: 5030
    cpu_shares: 1024
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-memory-interface:
    image: python:slim
    container_name: plugin-memory-interface
    volumes:
      - ./../pkg/plugin-memory-interface:/app
    working_dir: /app
    ports:
      - "5005:5005"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://memory:5006'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  memory:
    image: datasetteproject/datasette:0.64.3
    container_name: memory
    volumes:
      - ./../pkg/memory/data:/data
      - ./../pkg/memory:/app
    working_dir: /app
    ports:
      - "5006:5006"
    command: >
      /bin/sh -c "apt-get update && apt-get install -y procps 
      && pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'datasette' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

## COMMUNICATION
  yggdrasil-registry:
    build:
      context: ../pkg/yggdrasil-registry
    container_name: yggdrasil-registry
    volumes:
      - ./../pkg/yggdrasil-registry:/app
    ports:
      - "5500:5500"
      - "5501:5501"
    environment:
      OPENAI_API_KEY: ''
      PORT: 5500
      TOPIC: ''
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

networks:
  default:
    name: Yggdrasil