# docker-compose.yaml
version: '3.9'

services:
  plugin-manage-files:
    image: python:slim
    container_name: plugin-manage-files
    working_dir: /app
    volumes:
      - ./../pkg/plugin-manage-files:/app
    ports:
      - "5101:5003"
    command: >
      /bin/sh -c "python -m venv venv 
      && . venv/bin/activate 
      && python --version
      && pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-send-ntfy:
    image: python:slim
    container_name: plugin-send-ntfy
    working_dir: /app
    volumes:
      - ./../pkg/plugin-send-ntfy:/app
    ports:
      - "5003:5003"
    command: >
      /bin/sh -c "pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3
      
