# docker-compose.yaml
version: '3.9'

services:
  function-chat:
    image: python:slim
    container_name: function-chat
    working_dir: /app
    volumes:
      - ./../pkg/function-chat:/app
    environment:
      MEMORY_HOST: 'http://memory:8001'
      OPENAI_API_KEY: ''
      OPENAI_ORGANIZATION: ''
      OPENAI_MODEL: ''
    ports:
      - "5009:5009"
    command: >
      /bin/sh -c "pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

## -- COMMUNICATION SECTION -- ##
  communication-hub:
    image: python:slim
    container_name: communication-hub
    working_dir: /app
    volumes:
      - ./../pkg/communication-hub:/app
    command: >
      /bin/sh -c "pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 256
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  plugin-send-ntfy:
    image: python:slim
    container_name: plugin-send-ntfy
    working_dir: /app
    volumes:
      - ./../pkg/plugin-send-ntfy:/app
    ports:
      - "5003:5003"
    command: >
      /bin/sh -c "pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  function-log-communication:
    image: python:slim
    container_name: function-log-communication
    working_dir: /app
    volumes:
      - ./../pkg/function-log-communication:/app
    ports:
      - "5000:5000"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

## -- MEMORY SECTION -- ##
  plugin-memory-interface:
    image: python:slim
    container_name: plugin-memory-interface
    volumes:
      - ./../pkg/plugin-memory-interface:/app
    working_dir: /app
    ports:
      - "5005:5005"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    depends_on:
      - memory
    environment:
      MEMORY_HOST: 'http://memory:8001'
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

  memory:
    image: datasetteproject/datasette:0.64.3
    container_name: memory
    volumes:
      - ./../pkg/memory/data:/data
      - ./../pkg/memory:/app
    working_dir: /app
    ports:
      - "5006:8001"
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'datasette' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3

## -- HELPER PLUGINS -- ##
      
  plugin-request:
    image: python:slim
    container_name: plugin-request
    working_dir: /app
    volumes:
      - ./../pkg/plugin-request:/app
    ports:
      - "5200:5200"
    command: >
      /bin/sh -c "pip install -r requirements.txt 
      && python -u main.py"
    cpu_shares: 1024
    healthcheck:
      test: 
        - CMD-SHELL
        - pgrep -f 'main.py' || exit 1
      interval: 2s
      timeout: 2s
      retries: 3