openapi: 3.0.1
info:
  title: Memory Service API
  version: 'v1'
servers:
  - url: http://localhost:5006
paths:
  /{database}.json:
    get:
      operationId: listTables
      tags:
        - Knowledge
      parameters:
      - name: database
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /{database}/{table}.json:
    get:
      operationId: listRows
      tags:
        - Knowledge
      parameters:
      - name: database
        in: path
        required: true
        schema:
          type: string
      - name: table
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /{database}/{table}/{id}.json:
    get:
      operationId: getRow
      tags:
        - Knowledge
      parameters:
      - name: database
        in: path
        required: true
        schema:
          type: string
      - name: table
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK